version: '3.8'

services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio-website
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - portfolio-network

networks:
  portfolio-network:
    driver: bridge
